name: Deploy Vulnerable Application

on:
  push:
    branches: [ "main" ]


# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Run docker image
        run:  |
          docker pull securecodebox/bodgeit 
          docker run -d -p 8080:8080 securecodebox/bodgeit
          
      - name: Perform ZAP full scan
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          target: 'http://localhost:8080/' 
      
      
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project test.
